### ISSUE TITLE
Repo appearing empty on kodi when offshoregit.com is offline

### ISSUE THREAD

**Issue by pitsi** [lambda81/lambda-repo#5]
As the title implies, your repo appears empty when the offshoregit mirror is offline. It is now offline for instance (2015-07-02 06:57:26 UTC) and there is absolutely nothing to see or install in kodi. All other network related stuff, like retrieving the feeds, installing from the main kodi repo etc works flawlessly.

I did some search about it and I would suggest removing the following lines from addon.xml

		<info compressed="false">https://offshoregit.com/lambda81/lambda-repo/addons.xml</info>
		<checksum>https://offshoregit.com/lambda81/lambda-repo/addons.xml.md5</checksum>
		<datadir zip="true">https://offshoregit.com/lambda81/lambda-repo/</datadir>

It did work for me, twice, because it "forced" kodi to use github as the mirror for your repo.

It is my first report ever on github, so I am sorry if I have not used code tags or something.
Thank you in advance.

**Comment by UberNewf** [comment]
I had the same issue yesterday as well and changed the lines mentioned above to point to GitHub instead of offshoregit. Made it work. I wonder why offshoregit is used here at all - is there a reason not to point everything to GitHub? I too did some searching and found repeated reports of this "empty repo" issue and they correlated to down-times of offshoregit (which seems to be down *a lot*).

**Comment by s7eele** [comment]
as you may have heard there have been some server issues, can I ask if this issue has been resolved? there is a reason for using og vs git but I want to verify before I answer to minimise chances of looking stupid ;-)

**Comment by UberNewf** [comment]
It is resolved now. High chance of recurrence when OG is offline though.

**Comment by lambda81** [comment]
I am closing this issue, since it seems to be fixed.
